### ISSUE TITLE
Proposed Face test categories

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-toolboxes#17]
Based on the discussion in #16, here are the proposed categories for the Face Toolkit.

**2D Tests**
1. Low-res (front-facing) camera printout
2. Low-res camera video
3. High-res (rear-facing or DSLR) camera printout
4. High-res camera video

**3D tests**
5. Partial photo mask (partial mask placed over attacker's face, wrapped around)
6. Wrapped photo mask (full photo, wrapped around person or doll/mannequin head)
7. Custom wearable mask (Nils had provided a link for a place where you could purchase such a mask)

**Comment by woodbe** [comment]
This removes the 3D printing, and I didn't include a clay model, but I did put something like a doll head in as part of #6 

I'm not completely sure about the wearable mask. The site isn't fully working (lots of dead images), and off hand I didn't see a competitor on a search anyway), so I do not know if this is really workable.

**Comment by n-kai** [comment]
[1] created PAIs in realistic mobile biometric verification scenarios by considering the following factors.

**Enrollment**
1. 20 test subjects
1. 3 different illumination conditions
Each test subject enrolls under the 3 different illumination conditions. So total number of enrollment template is 3 X 20 = 60

**PAI creation**
1. Capture the test subject’s high-resolution photo and video with one mobile device under the 3 different illumination condition
1. Use two different printers to make print attack PAIs
Total number of print attack PAIs is 3 X 20 X 2 = 120
1. Use two displays to make video-replay attack PAIs
Total number of video-replay attack PAIs is 3 X 20 X 2 = 120

So [1] didn't create "2. Low-res camera video" because such low quality PAI can be easily detected. So I recommend removing "2. Low-res camera video" from 2D test and concentrate on High-res print and video-replay with different conditions (illumination, camera, printer and display). 

I propose to discuss this issue at the Singapore.

[1] 6.3 The OULU-NPU face PAD database
http://jultika.oulu.fi/files/isbn9789526219257.pdf

**Comment by woodbe** [comment]
To be discussed further at the CCUF meeting.

@woodbe proposes to make changes to the https://github.com/biometricITC/cPP-toolboxes/blob/develop/toolbox.adoc document that would list environmental conditions as subject to the specific modality to create additional PAI from what would be expected just based on the toolbox overview itself.

**Comment by woodbe** [comment]
General consensus on 3 test subjects for each modality to be updated in the toolbox document.

Look at adding selection criteria for test subjects (ethnicity, age, gender, etc) for the 3 test subjects within each toolbox-specific overview.

@woodbe will make the update

**Comment by woodbe** [comment]
closing based on the current face toolbox has resolved this discussion
