### ISSUE TITLE
PAI from printed photos

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-toolboxes#7]
Currently in the eye and face (2D, anyway) toolboxes, we have tests that take a printed photo, then scan it and in some cases re-print it, possibly after some processing on the computer. 

My question is, does this really serve any testing purpose? I get that taking a photo and scanning it could be a way to get someone's face picture (harder for the eyes I think, but still), but this test almost seems more about the ability of the computer to scale a small photo to a larger one without major artifacts than anything else. 

I think in the end what bothers me most about this is that if a sensor fails here, with a likely more degraded image (given the photo, then scan, then process then print again), that it is seems likely to not pass the single print versions. (I'm talking about the 1-X vs the 2-X series of tests.)

It seems like a lot of busy work to take a photo, scan it, mess with it (like cropping, etc) and then print it again to see if it works. Taking the picture in the first place, doing any editing and then printing and trying seems like a better use of time (and anything that passes the 2-X tests would seem extremely unlikely to fail a 1-X test set).

**Comment by n-kai** [comment]
@woodbe 
I am not sure this is the right answer for your question but I drafted the 2D face toolbox (@stemotre created her version based on this) considering the result of discussion at Berlin CCUF workshop last year. At the meeting we agreed;
1) develop toolbox that lists **common minimum PAIs** that the mobile device shall detect.
2) in principle this **common minimum PAIs** should be determined by the CC/CEM (i.e. attack potential) but we should also consider the current level of technology (you said that PAD technology was not mature and it's not possible to detect all PAI because of, for example, the technical limitation of embedded sensors in the mobile devices (e.g. fingerprint sensor was too small and could not gain fingerprint images clear enough to detect all fake fingerprint)
3) however we couldn't reach a consensus about what this **common minimum PAIs** was at the Berlin meeting.

So when I drafted the 2D face toolbox, I included various type of PAIs, from low quality PAI (e.g. printed face created by the low resolution photo) to high quality PAI (e.g. take high resolution video of the target user face and display it to the TOE) in the toolbox because I didn't know what **common minimum PAIs** was for the 2D face recognition at that time.

So I agree to remove some low quality PAIs from toolbox to reduce the number of PAIs. But problem is how we can do that.  You proposed to develop the "Camera toolbox" which can be shared among different toolboxes and I don't know which should be done first but we can discuss this at the next call.

**Comment by woodbe** [comment]
@n-kai My immediate thinking was to just remove the ones from taking an already printed photo and then scanning and reprinting it. I didn't have a problem taking a printed photo and testing, just not taking a photo, printing it, scanning it, and printing it again. I agree that we should discuss where to draw the line, as this is something that is not necessarily an easy thing.

**Comment by n-kai** [comment]
OK, I will propose how to reorganize the toolbox to address issues after the ballot is closed.

**Comment by woodbe** [comment]
Closing as this specific type of test has been agreed to be removed from the toolboxes.
