### ISSUE TITLE
Transaction vs Match in results

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-toolboxes#9]
@nils-tekampe I have never fully grasped the difference between a transaction and a match for the testing process. I don't know if it matters one way or the other, but could you briefly describe the difference? Either way we should describe it in the toolbox overview so it is clearly understood what the expectation is for the successful result.

**Comment by nils-tekampe** [comment]
Sure, no problem. Let’s assume a biometric verification system with one enrolled user A.
I a user uses a biometric system he makes one attempt. He simply asks the biometric system to verify the identity once. The system answers yes or no. 
The chance that a legitimate attempt fails (a false non match) is called false non match rate. The chance that an attempt of an unauthorized user has success (a false match) ist called false match rate.

Many biometric systems allow more than one attempt if the attempt fails before they block access. This way, the systems combine up to x attempts to one transaction. If an attempt if the user fails, he has a second or a third chance.
Transactions then have corresponding errror rates, namely the FRR and FAR.

When talking about testing, it is most often just important to be very precise what you are asking for, I made the experience that many people say attempt when meaning transaction and vice versa. When I ask somebody whether he or she really means an attempt or a transaction this does usually not mean that I prefer the one or the other. I’m just a nit-picker :-)

BTW: when talking about transactions, one needs to know about the system policy. I.e. how many attempts the system allows. When talking about generic test requirements this is almost never known. For this reason you will often end up with attempts.

**Comment by woodbe** [comment]
OK, that makes sense, but my follow-up question would be (I think) is where is the "transaction counter" handled? If this is part of the biometric system then I would see transactions as being useful (maybe), but if that is handled outside, then what is the thinking?

So if I say an attempt is any time the sensor is triggered as far as the biometric system is concerned (i.e. whether user A tries to login or if something brushed against the sensor that triggered it is still an attempt), but that the system as a whole allows 5 attempts before say a block (i.e. the user must then enter a password, or has to wait 30 seconds, something), are these treated differently in this case? 

I agree that in either case there needs to be some sort of description of the system, but it would seem that if the "counter" is inside the biometric system then you want transactions, and if it isn't, you want matches?

**Comment by nils-tekampe** [comment]
This is not longer one question :-) 

1) yes, for transactions, the system need to maintain a counter. 
2) I have to admit that I’m not sure whether „something brushed by the sensor“ would count as an attempt. I would need to check the standard for this question. But it is definitely possible that the system recognizes it as an attempt. 
3) yes and no: if you have no Counter in the system, you will have to use attempts. But there are plenty of cases where systems that support transactions still have requirements on the attempt level. A classical example could be to make two or more systems that have different transaction policies comparable.

**Comment by n-kai** [comment]
@woodbe 

 _So if I say an attempt is any time the sensor is triggered as far as the biometric system is concerned (i.e. whether user A tries to login or if something brushed against the sensor that triggered it is still an attempt), but that the system as a whole allows 5 attempts before say a block (i.e. the user must then enter a password, or has to wait 30 seconds, something), are these treated differently in this case?_

The developer gathers the test subjects to perform the performant testing to measure the FAR/FRR. Enough instructions and training shall be given to the test subjects before the testing (See [7.3.4](https://github.com/biometricITC/cPP-biometrics/blob/master/4_Methodology/BS_SD.adoc#734-td4-test-instructions-and-training)). The developer can advice the test subject to prevent "something brushed against the sensor" before or during the testing (See [7.3.6 d](https://github.com/biometricITC/cPP-biometrics/blob/master/4_Methodology/BS_SD.adoc#736-td6-test-procedure)).
If the test subject follows the test instruction correctly (i.e. he/she presents the biometric characteristics to the TOE correctly) but the "something brushed against the sensor" during the testing, such attempt should be counted as one failed attempt because the sensor is too sensitive and such things can also be happened at the normal operation.
This kind of testing is called "scenario testing" that testing is carried out in an environment that models a
real-world target application of interest and the SD assumes that the developer conducts this "scenario testing"  to measure the FAR/FRR.

**Comment by woodbe** [comment]
Ok, so I see how the "non-attempt attempt" can be ignored or counted as needed (and likely just avoided as far as testing goes here), so I guess the question of attempt vs transaction is then solely dependent on where the counter is maintained (since obviously authentication systems have a counter), the question is is whether the system as a whole, meaning in this case the mobile device has the counter and so treats any one attempt with the biometric as a count or if the biometric system has its own counter and counts multiple attempts to one transaction and then reports transactions to the mobile device as a device-level attempt.

So this really just comes down to how the vendor sets up the system and makes selections in FIA_MBV_EXT.1 (based on my re-read of [SD 8](https://github.com/biometricITC/cPP-biometrics/blob/master/4_Methodology/BS_SD.adoc#8-requirement-for-the-number-of-test-subject-transaction-and-samples).

Unless I'm missing something then, my question has been answered and I don't see any specific point that needs to be updated/changed.
